# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Deno deploy api+browser

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - "tests"

jobs:
  deploy:
    # Can switch to ubuntu-latest but self-hosted is safer and faster
    name: npm publish
    runs-on: [self-hosted]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: publish version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: just publish
